---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-jenkins-vm
    image: leandelivery/docker-systemd:centos7
    privileged: True
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8888:8080/tcp
    groups:
      - jenkins_master
      - rhel_family
  - name: test-jenkins-slave-centos7-vm
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - jenkins_slaves
      - rhel_family
  - name: test-jenkins-slave-ubuntu18-vm
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - jenkins_slaves
      - debian_family
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: prepare.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/docker_tests/
  lint:
    name: flake8
