---
- name: "Create jenkins user"
  user:
    name: "{{ slave_linux_jenkins_username }}"
    group: docker
    password: "!"
    home: /var/lib/jenkins
    state: present
  become: True

- name: "Set authorized key"
  authorized_key:
    user: "{{ slave_linux_jenkins_username }}"
    state: present
    key: "{{ slave_linux_jenkins_public_key }}"
  become: True
  when: slave_linux_jenkins_public_key | trim

- name: "Install slave jenkins agent"
  jenkins_script:
    user: "{{ master_username }}"
    password: "{{ master_password }}"
    validate_certs: False
    timeout: 120
    url: "{{ master_url }}"
    script: "{{ lookup('template', 'add_linux_slave.groovy.j2') }}"

- name: "Add selinux support"
  include_tasks: selinux-support.yml
  when: ansible_os_family == "RedHat"
